<?php
// $Id$

// lis_species_resources

// Sudhansu Dash
// 2016 Mar 10


/**
 * Implements hook_menu().
 */

function lis_species_resources_menu() {
  $items = array();
  $items['species'] = array( //this creates a URL for the species page
  //$items['lis_species_resources'] = array( //this creates a URL for the species page
    'title' => 'Available resources for legume species', //page title
    'description' => 'Creates html for the lis species page listing the resources available for a species from an excel sheet.',
    'page callback' => lis_species_resources_page_callback, //this fn is called when page accessed. For form, use drupal_get_form
    //'page arguments' => array('grin_acc_query_form'), //form name here; no need if page callback fn() doesn't need it.
    'access callback' => TRUE,
  );

  //$items['lis_species_resources_genomes'] = array( //this creates a URL for genome page
  $items['genomes'] = array( //this creates a URL for genome page

    'title' => 'Genome Browsers at LIS and sister sites', //page title
    'description' => 'Creates html for the lis genomes page listing the genome links per species from the same excel sheet.',
    //'page callback' => lis_species_resources_genomes_page_callback, //this fn is called when page accessed. For form, use drupal_get_form
    'page callback' => lis_species_resources_genomes_page_callback,
    
    //'page arguments' => array('grin_acc_query_form'), //form name here; no need if page callback fn() doesn't need it.
    'access callback' => TRUE,
  );


  return $items;
}


/**
 * Implements hook_theme().
 */


function lis_species_resources_theme() {
  return array(
    'lis_species_resources_page_template' => array(  // this array name to be used in theme() fn.
    'template' => 'lis_species_resources_page',  //template file lis_species_resources_page.tpl.php
    //'variables' => array('var1 => NULL', 'var2 => NULL' ),
    ),  //array page_template
    
    'lis_species_resources_genomes_page_template' => array(  // this array name to be used in theme() fn.
    'template' => 'lis_species_resources_genomes_page',  //template file lis_species_resources_page.tpl.php
    //'variables' => array('var1 => NULL', 'var2 => NULL' ),
    ),  //array page_template

  );  // array return
}    

/**
 * Implements page callback.
 */

function lis_species_resources_page_callback() {
    
    // load phpexcel drupal module
    module_load_include('inc', 'phpexcel');  
    // The path to the excel file
    $module_path = drupal_get_path('module', 'lis_species_resources');
    //drupal_set_message(t($module_path));
    $species_resources_path = "files/lis_species_resources";
    $excel_file = "lis_species_features.xlsx";
    $excel_worksheet = "sheet1_species"; //name of specific worksheet in the excel file
    //$excel_file_path = $module_path."/".$excel_file; 
    $excel_file_path = $species_resources_path."/".$excel_file; 
    //drupal_set_message(t("\$excel_file_path: "."webroot/".$excel_file_path));
    
    
    //IMPORT
        // phpexcel_import('path-to-excel',TRUE,TRUE)
            //FALSE in 2nd arg implies the header row is read as just another row; 2nd arg if TRUE
        //EXAMPLE for importing specific worksheet:
           //phpexcel_import('path/to/file.xls', TRUE, TRUE, array('setLoadSheetsOnly' => array('My sheet')));
        //$excel_array = phpexcel_import($excel_file_path,FALSE,TRUE);  //now excel file content in an array
        //$excel_array = phpexcel_import($excel_file_path,TRUE,TRUE);  //now excel file content in an array
    
    //Importing a specific worksheet
    $excel_array = phpexcel_import($excel_file_path,TRUE,TRUE, array('setLoadSheetsOnly' => array($excel_worksheet)));  //now excel file content in an associative array with keys as in 1st row of sheet
    $excel_array = $excel_array[$excel_worksheet];  //entered into the next evel(worksheet) in the array
    
    //Ensure it is an array or create error
    if (is_array($excel_array)) {
        //drupal_set_message(t("OK: now in array"));  //File content now in array
        
        //extract the keys: (Not using them currently)
        $sheet_keys = array_keys($excel_array[0]); //array
            //print_r($sheet_keys);
        
        $species_html = "";
        
        //Entering into the array row by row
        foreach ($excel_array as $row) {
            
            //Skip rows with # in first column (comment rows)
            if (preg_match("/\#/", $row['rowCode'])) {
                continue;
            }
            
            if ($row['rowCode'] == 1) {
                    
                
                
                //species subheading
                $species_html .= "<dl  class='dl_no_break'>";
                $species_html .= "<dt>"."<i>".$row['sciName']."</i>"."  "."(<b>".$row['commonName']."</b>)"; //species subheading
                
                //About
                //http://localhost:8888/organism/Medicago/truncatula
                $species_html .= " - "."<a  href=\""."/organism/".$row['genus']."/".$row['species']."\"".">"."About"."</a>"."</dt>";
                $genus = $row['genus'];
                $species = $row['species'];
                
                //browse genome
                if ($row['gbrowseKey'] || $row['jbrowseKey']) {
                    $species_html .= "<dd>Browse genome:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;";
                
                    if ($row['gbrowseKey']) {
                        $species_html .= "".makeGbrowseKey($row['gbrowseKey'])."";
                    } //if-gbrowse
                    $species_html .= "&nbsp;&nbsp;&nbsp;";
                    if ($row['jbrowseKey']) {
                        $species_html .= "".makeJbrowseKey($row['jbrowseKey'])."";
                    } //if-gbrowse
                    
                    $species_html .= "</dd>";
                } //if-genomes
                
                //Genes
                //http://localhost:8888/search/gene?abbreviation=Cic.+arietinum
                if ($row['genesKey']) {
                    $species_html .= "<dd>"."<a  href="."\""."search/gene?abbreviation=".$row['genesKey']."\"".">"."Genes"."</a>"."</dd>";
                }
                
                //Maps
                if ($row['mapsKey']) {
                    $species_html .= "<dd>"."<a  href="."\""."traits_maps#".$row['mapsKey']."\"".">"."Maps"."</a>"."</dd>";
                }

        		//QTL
                //http://localhost:5666/search/qtl?organism=Phaseolus+vulgaris
                if ($row['QTL'])  {
                    $species_html .= "<dd>"."<a  href="."\""."search/qtl?organism=".$row['genus']."+".$row['species']."\"".">"."QTL"."</a>"."</dd>";
                }
                
                //ExternalGenome1
                if ($row['externalGenome1']) {
                    $parts = explode ('::',$row['externalGenome1'] );
                    $label = $parts[0];
                    $link = $parts[1];
                    $species_html .= "<dd>"."<a  target=\"_blank\"  href="."\"".$link."\"".">".$label."</a>"."</dd>";
                }
                
                //ExternalGenome2
                if ($row['externalGenome2']) {
                    $parts = explode ('::',$row['externalGenome2'] );
                    $label = $parts[0];
                    $link = $parts[1];
                    $species_html .= "<dd>"."<a  target=\"_blank\"  href="."\"".$link."\"".">".$label."</a>"."</dd>";
                }
                        
                //ExternalGenome3
                if ($row['externalGenome3']) {
                    $parts = explode ('::',$row['externalGenome3'] );
                    $label = $parts[0];
                    $link = $parts[1];
                    $species_html .= "<dd>"."<a  target=\"_blank\"  href="."\"".$link."\"".">".$label."</a>"."</dd>";
                }
        
                //DataStore
                if ($row['dataStore']) {
                    $species_html .= "<dd>"."<a  href="."\""."data/public/".$row['genus']."_".$row['species']."/"."\"    ".">"."Download Data from Data Store"."</a>"."</dd>";
                }
                
                //Mines
                if ($row['minesKey']) {
                    $species_html .= "<dd>"."<a  target=\"_blank\"  href=https://mines.legumeinfo.org/".$row['minesKey']."/begin.do".">".$row['minesKey']."</a>"."</dd>";
                }
		
		//Extra1
                if ($row['extra1']) {
                    $parts = explode ('::',$row['extra1'] );
                    $label = $parts[0];
                    $link = $parts[1];
                    $species_html .= "<dd>"."<a  target=\"_blank\"  href="."\"".$link."\"".">".$label."</a>"."</dd>";
                }
        
                //Extra2
                if ($row['extra2']) {
                    $parts = explode ('::',$row['extra2'] );
                    $label = $parts[0];
                    $link = $parts[1];
                    $species_html .= "<dd>"."<a  target=\"_blank\"  href="."\"".$link."\"".">".$label."</a>"."</dd>";
                }
                
                //Extra3
                if ($row['extra3']) {
                    $parts = explode ('::',$row['extra3'] );
                    $label = $parts[0];
                    $link = $parts[1];
                    $species_html .= "<dd>"."<a  target=\"_blank\"  href="."\"".$link."\"".">".$label."</a>"."</dd>";
                }
 
 		//Extra4
                if ($row['extra4']) {
                    $parts = explode ('::',$row['extra4'] );
                    $label = $parts[0];
                    $link = $parts[1];
                    $species_html .= "<dd>"."<a  target=\"_blank\"  href="."\"".$link."\"".">".$label."</a>"."</dd>";
                }
                //Extra5
                if ($row['extra5']) {
                    $parts = explode ('::',$row['extra5'] );
                    $label = $parts[0];
                    $link = $parts[1];
                    $species_html .= "<dd>"."<a  target=\"_blank\"  href="."\"".$link."\"".">".$label."</a>"."</dd>";
                }
 
		//Extra6
                if ($row['extra6']) {
                    $parts = explode ('::',$row['extra6'] );
                    $label = $parts[0];
                    $link = $parts[1];
                    $species_html .= "<dd>"."<a  target=\"_blank\"  href="."\"".$link."\"".">".$label."</a>"."</dd>";
                }
 
                
                //EXPRESSION DATASETS IF ANY
                //$sql_expr_datasets = "SELECT od.accession_no FROM ongenome.dataset AS od WHERE od.genome_id IN (SELECT og.genome_id FROM ongenome.genome AS og WHERE og.organism_id IN (SELECT oo.organism_id from ongenome.organism AS oo WHERE oo.genus="."'".$genus."'"." AND oo.species="."'".$species."'"."))";
                $sql_expr_datasets = "SELECT od.accession_no FROM ongenome.dataset AS od WHERE od.genome_id IN (SELECT og.genome_id FROM ongenome.genome AS og WHERE og.organism_id IN (SELECT oo.organism_id from ongenome.organism AS oo WHERE oo.genus= :genus AND oo.species= :species))";
                
                
                $expr_datasets = db_query($sql_expr_datasets, array(':genus' => $genus, ':species' => $species))->fetchCol();
                //print gettype($expr_datasets);
                //print_r( $expr_datasets);
                if ($expr_datasets) { 
                    $species_html .= "<dd>Expression Datasets: ";
                    foreach ($expr_datasets as $ds) {
                        $species_html .= "<a href=\"lis_expression/all#". $ds . "\">". $ds . "</a>" . "&nbsp&nbsp";
                    }
                    $species_html .= " </dd>";
                    
                }




                $species_html .= "</dl>";
                
            } //if rowcode =1 
          
        }  //foreach row
        //>>>>>>>>>>>>
        
      
    }
    else {
      drupal_set_message(t("Oops ! An error occured in accesing ".$excel_file." or some errors!"), 'error');
    }
  
    //echo gettype($excel_array);
    /*
    echo "<pre>";
    print_r($excel_array);
    echo "</pre>";
    */



    
    
  //===========================================================================
  // array name in hook_theme() that specifies page template file.
  return theme ('lis_species_resources_page_template', array('excel_array' => $excel_array, 'worksheet_array' => $worksheet_array, 'headers_array' => $headers_array, 'species_html' => $species_html)); 


}


/*  2nd callback for genome */
//<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
/**
* Implements page callback. genomes page
*/

function lis_species_resources_genomes_page_callback() {

// load phpexcel drupal module
module_load_include('inc', 'phpexcel');  
// The path to the excel file
$module_path = drupal_get_path('module', 'lis_species_resources');
//drupal_set_message(t($module_path));
$species_resources_path = "files/lis_species_resources";
$excel_file = "lis_species_features.xlsx";
$excel_worksheet = "sheet1_species"; //name of specific worksheet in the excel file
//$excel_file_path = $module_path."/".$excel_file; 
$excel_file_path = $species_resources_path."/".$excel_file; 
//drupal_set_message(t("\$excel_file_path: "."webroot/".$excel_file_path." (Exact same as the species page excel file)."));


//IMPORT
    // phpexcel_import('path-to-excel',TRUE,TRUE)
	//FALSE in 2nd arg implies the header row is read as just another row; 2nd arg if TRUE
    //EXAMPLE for importing specific worksheet:
       //phpexcel_import('path/to/file.xls', TRUE, TRUE, array('setLoadSheetsOnly' => array('My sheet')));
    //$excel_array = phpexcel_import($excel_file_path,FALSE,TRUE);  //now excel file content in an array
    //$excel_array = phpexcel_import($excel_file_path,TRUE,TRUE);  //now excel file content in an array

//Importing a specific worksheet
$excel_array = phpexcel_import($excel_file_path,TRUE,TRUE, array('setLoadSheetsOnly' => array($excel_worksheet)));  //now excel file content in an associative array with keys as in 1st row of sheet
$excel_array = $excel_array[$excel_worksheet];  //entered into the next evel(worksheet) in the array

//Ensure it is an array or create error
if (is_array($excel_array)) {
    //drupal_set_message(t("OK: now in array")); // file content now in array
    
    //extract the keys: (Not using them currently)
    $sheet_keys = array_keys($excel_array[0]); //array
	//print_r($sheet_keys);
    
    //$genomes_html = "<table>";
    $genomes_html = "";

    
    //Entering into the array row by row
    foreach ($excel_array as $row) {
	
	//Skip rows with # in first column (comment rows)
        if (preg_match("/\#/", $row['rowCode'])) {
            continue;
        }
	        //Only consider rows starting with 1 (prevents blank spreadsheet rows from showing up)
            //Skip rows that don't have gbrowse or jbrowse or externalGenome1
        if ($row['rowCode'] == 1 && $row['gbrowseKey'] || $row['jbrowseKey'] || $row['externalGenome1']) {  
            
            
            //species subheading
            //$genomes_html .= "<tr>";
            $genomes_html .= "<dl  class='dl_no_break'>";
            //$genomes_html .= "<td style='width:100px;'>"."<i>".$row['sciName']."</i>"." <br/> "."(<b>".$row['commonName']."</b>)"."</td>"; //species subheading
            $genomes_html .= "<dt>"."<i>".$row['sciName']."</i>"."  "."(<b>".$row['commonName']."</b>)"."</dt>"; //species subheading"

           /* //About
            //http://localhost:8888/organism/Medicago/truncatula
            $species_html .= " - "."<a  href=\""."/organism/".$row['genus']."/".$row['species']."\"".">"."About"."</a>"."</dt>";*/
            
            //browse genome
           
            if ($row['gbrowseKey']) {
                //$genomes_html .= "<td style='width:100px'>".makeGbrowseKey($row['gbrowseKey'])." (".$row['jbrowseKey'].")"."</td>";
                $genomes_html .= "<dd>".makeGbrowseKey($row['gbrowseKey'])." (".$row['jbrowseKey'].")"."</dd>";

            } //if-gbrowse
            //$genomes_html .= "&nbsp;&nbsp;&nbsp;";
            
            if ($row['jbrowseKey']) {
                //$genomes_html .= "<td style='width:100px'>".makeJbrowseKey($row['jbrowseKey'])." (".$row['jbrowseKey'].")"."</td>";
                  $genomes_html .= "<dd>".makeJbrowseKey($row['jbrowseKey'])." (".$row['jbrowseKey'].")"."</dd>";

            } //if-jbrowse
            
            
            //Extra1
            if ($row['externalGenome1']) {
            $parts = explode ('::',$row['externalGenome1'] );
            $label = $parts[0];
            $link = $parts[1];
            //$genomes_html .= "<td style='width:180px'>"."<a  target=\"_blank\"  href="."\"".$link."\"".">".$label."</a>"."</td>";
            $genomes_html .= "<dd>"."<a  target=\"_blank\"  href="."\"".$link."\"".">".$label."</a>"."</dd>";

            }
            
            //Extra2
            if ($row['externalGenome2']) {
            $parts = explode ('::',$row['externalGenome2'] );
            $label = $parts[0];
            $link = $parts[1];
            //$genomes_html .= "<td>"."<a  target=\"_blank\"  href="."\"".$link."\"".">".$label."</a>"."</td>";
            $genomes_html .= "<dd>"."<a  target=\"_blank\"  href="."\"".$link."\"".">".$label."</a>"."</dd>";

            }
            
            //Extra3
            if ($row['externalGenome3']) {
            $parts = explode ('::',$row['externalGenome3'] );
            $label = $parts[0];
            $link = $parts[1];
            //$genomes_html .= "<td>"."<a  target=\"_blank\"  href="."\"".$link."\"".">".$label."</a>"."</td>";
            $genomes_html .= "<dd>"."<a  target=\"_blank\"  href="."\"".$link."\"".">".$label."</a>"."</dd>";

            }
    
    
            //$genomes_html .= "</tr>";
            $genomes_html .= "</dl>";

            
        } //if rowcode =1 
      
    }  //foreach row
    
    //$genomes_html .= "</table>";
    //>>>>>>>>>>>>
        
      
    }
    else {
      drupal_set_message(t("Oops ! An error occured in accesing ".$excel_file." or some errors!"), 'error');
    }
  
    //echo gettype($excel_array);
    /*
    echo "<pre>";
    print_r($excel_array);
    echo "</pre>";
    */



    
    
  //===========================================================================
  // array name in hook_theme() that specifies page template file.
  return theme ('lis_species_resources_genomes_page_template', array('excel_array' => $excel_array, 'worksheet_array' => $worksheet_array, 'headers_array' => $headers_array, 'species_html' => $genomes_html)); 


}


/*
 *Helper functions
 *
 */
/*
//old
function makeGbrowseKey ($string) {
            $string = "<a href=\"/gbrowse_".$string."\">"."GBrowse"."</a>";
            return $string;
        }
*/
function makeGbrowseKey ($string) {
            $string = "<a href=\"/genomes/gbrowse/".$string."\">"."GBrowse"."</a>";
            return $string;
        }
        
function makeJbrowseKey ($string) {
            $string = "<a href=\"/genomes/jbrowse/?data=".$string."\">"."JBrowse"."</a>";
            return $string;
        }


//  SCRATCH PAD
//=============

/*
 

*/
